
development:
  adapter: mysql2
  encoding: utf8
  database: freezing-adventure_dev
  username: root
  password: "123456"
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: freezing-adventure_test
  username: root
  password: "123456"
  host: 127.0.0.1
  
production:
  adapter: mysql2
  encoding: utf8
  database: freezing-adventure_production
  username: root
  password: "123456"
  host: 127.0.0.1